### PR TITLE
[schunk] Add TCP/IP interface (for use of Lua script)

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Anzu PR 10861

- - -
This change is [Reviewable](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24#-NlVPYBtEaooSHxK9oJP:-NlVPYBuDYSKwNHq-xNN:b4uwb4g) (no related file):*
Working: Needs change for ROS node.

___
___
*[`schunk_wsg_driver/src/schunk_wsg_driver/schunk_wsg_driver_common.cpp` line 192 at r1](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24#-NlVPePl82kHh7FYUGy-:-NlVPePm9QJUztcRUd57:blimycp) ([raw file](https://github.com/ToyotaResearchInstitute/tri_hardware_drivers/blob/85078cda7019db407b1314eee43ba2a83c910716/schunk_wsg_driver/src/schunk_wsg_driver/schunk_wsg_driver_common.cpp#L192)):*
> ```cpp
>   // const WSGRawCommandMessage stop_command(kStop);
>   // TODO(eric.couisneau): Why? I dunno.
>   const WSGRawCommandMessage stop_command(kDisconnectAnnounce);
> ```

@calderpg-tri This may be the main sticking point for this PR.

From what I remember, resuming drivers did not work well unless I had this, at least for the script.
Do you want this to be an explicit flag?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24)* status: 0 of 6 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24#-NlVPYBtEaooSHxK9oJP:-NlVQjmL3f8_ZOtPA3iN:b-896fix) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Needs change for ROS node.
</blockquote></details>

Done.

___

**Review by EricCousineau-TRI — COMMENTED** [review]
+@calderpg-tri for review, please!

> *[Reviewable](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24#-:-NlVQuzb2Be1bSMTbC0l:bbnoq2u)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @calderpg-tri)

**Review by calderpg-tri — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24)* status: all files reviewed, 6 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[`schunk_wsg_driver/include/schunk_wsg_driver/schunk_wsg_driver_common.hpp` line 401 at r3](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24#-Nld6SPs67-MKDMZbNqL:-Nld6SPt-HGQcO_c2tD8:bcej8l8) ([raw file](https://github.com/ToyotaResearchInstitute/tri_hardware_drivers/blob/ada79b89aeb371bf214449c47b7dc98f73612ee8/schunk_wsg_driver/include/schunk_wsg_driver/schunk_wsg_driver_common.hpp#L401)):*
> ```cpp
> 
>   std::function<void(const std::string&)> logging_fn_;
>   bool enabled_recurring_status_{};
> ```

nit Elsewhere the style here would likely be `bool enabled_recurring_status_ = false;`
___
*[`schunk_wsg_driver/src/schunk_wsg_driver_node.ros1.cpp` line 147 at r3](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24#-Nld7P47DKkqUnY5xafo:-Nld7P47DKkqUnY5xafp:b91dk7d) ([raw file](https://github.com/ToyotaResearchInstitute/tri_hardware_drivers/blob/ada79b89aeb371bf214449c47b7dc98f73612ee8/schunk_wsg_driver/src/schunk_wsg_driver_node.ros1.cpp#L147)):*
> ```cpp
>       gripper_interface
>           = std::make_shared<schunk_wsg_driver::WSGTCPInterface>(
>               logging_fn, gripper_ip_address, gripper_port, local_port);
> ```

This doesn't take `local_port`
___
*[`schunk_wsg_driver/src/schunk_wsg_driver/schunk_wsg_driver_common.cpp` line 192 at r1](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24#-NlVPePl82kHh7FYUGy-:-NldA6bH8VxBj2lX2BiV:b-4ie7lr) ([raw file](https://github.com/ToyotaResearchInstitute/tri_hardware_drivers/blob/85078cda7019db407b1314eee43ba2a83c910716/schunk_wsg_driver/src/schunk_wsg_driver/schunk_wsg_driver_common.cpp#L192)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

@calderpg-tri This may be the main sticking point for this PR.

From what I remember, resuming drivers did not work well unless I had this, at least for the script.
Do you want this to be an explicit flag?
</blockquote></details>

So long as the behavior when running the driver directly (no script, normal ROS control) is OK, I think this is fine. There are some mentions in the documentation that suggest that stop and disconnect are the same for external control, but would produce different behavior with a script.
___
*[`schunk_wsg_driver/src/schunk_wsg_driver/schunk_wsg_driver_ethernet.cpp` line 145 at r3](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24#-NldCFr71hFK5LGauwbb:-NldCFr71hFK5LGauwbc:btk7mbo) ([raw file](https://github.com/ToyotaResearchInstitute/tri_hardware_drivers/blob/ada79b89aeb371bf214449c47b7dc98f73612ee8/schunk_wsg_driver/src/schunk_wsg_driver/schunk_wsg_driver_ethernet.cpp#L145)):*
> ```cpp
>       + gripper_ip_address + " gripper port " + std::to_string(gripper_port));
> 
>   struct hostent* nameserver = gethostbyname(gripper_ip_address.c_str());
> ```

This check should be the same for both UDP and TCP versions
___
*[`schunk_wsg_driver/src/schunk_wsg_driver/schunk_wsg_driver_ethernet.cpp` line 242 at r3](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24#-NldAzBWBLEWPjgAR9TR:-NldAzBWBLEWPjgAR9TS:b-pexwhd) ([raw file](https://github.com/ToyotaResearchInstitute/tri_hardware_drivers/blob/ada79b89aeb371bf214449c47b7dc98f73612ee8/schunk_wsg_driver/src/schunk_wsg_driver/schunk_wsg_driver_ethernet.cpp#L242)):*
> ```cpp
>   recv_thread_.join();
>   Log("Close socket...");
>   // TODO(eric.cousineau): Calling shutdown(socket_fd_, SHUT_RDWR) here causes
> ```

btw elsewhere `close(socket)` gets used, this should be fine?
___
*[`schunk_wsg_driver/src/schunk_wsg_driver/schunk_wsg_driver_ethernet.cpp` line 277 at r3](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24#-NldBZvy3gLvOIU61itw:-NldBZvy3gLvOIU61itx:bkzg0s2) ([raw file](https://github.com/ToyotaResearchInstitute/tri_hardware_drivers/blob/ada79b89aeb371bf214449c47b7dc98f73612ee8/schunk_wsg_driver/src/schunk_wsg_driver/schunk_wsg_driver_ethernet.cpp#L277)):*
> ```cpp
>   while (active_.load())
>   {
>     const ssize_t read_size = read(
> ```

I believe you need to reenable `TCP_QUICKACK` [after the read](https://github.com/ToyotaResearchInstitute/tri_hardware_drivers/blob/master/dji_robomaster_ep_driver/src/dji_robomaster_ep_driver/dji_robomaster_ep_driver.cpp#L334-L387)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @calderpg-tri and @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24#-NleFFG05uvu5M7p1bGo:-NleFFG05uvu5M7p1bGp:bn75d6r) (no related file):*
Working: Will re-test on Schunk.

___
___
*[`schunk_wsg_driver/include/schunk_wsg_driver/schunk_wsg_driver_common.hpp` line 401 at r3](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24#-Nld6SPs67-MKDMZbNqL:-NleEgUxDZ-tjz5se2eo:b-896fix) ([raw file](https://github.com/ToyotaResearchInstitute/tri_hardware_drivers/blob/ada79b89aeb371bf214449c47b7dc98f73612ee8/schunk_wsg_driver/include/schunk_wsg_driver/schunk_wsg_driver_common.hpp#L401)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

nit Elsewhere the style here would likely be `bool enabled_recurring_status_ = false;`
</blockquote></details>

Done.
___
*[`schunk_wsg_driver/include/schunk_wsg_driver/schunk_wsg_driver_common.hpp` line 414 at r4](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24#-NleElDB82Dd3Coo-714:-NleElDB82Dd3Coo-715:b-nj3sxc) ([raw file](https://github.com/ToyotaResearchInstitute/tri_hardware_drivers/blob/a35fc0c36db510824e21c7592a0bb51e3cf20b89/schunk_wsg_driver/include/schunk_wsg_driver/schunk_wsg_driver_common.hpp#L414)):*
> ```cpp
>   // Initialize gripper.
>   // @param update_period_ms Update period, namely used for recurring status.
>   // @param use_scripting_interface Set to true if using scripting to both send
> ```

FYI This setup is a bit convoluted; I am not sure if I should instead use a parameter struct to be more explicit, e.g.
```
struct InitializeGripperParam {
  uint16_t update_period_ms = 20;
  bool enable_recurring_status = true;
  GripperCommand stop_command = kStop;
};
```

Do you care for me to change it, or are you OK with me leaving this as-is?
___
*[`schunk_wsg_driver/src/schunk_wsg_driver_node.ros1.cpp` line 147 at r3](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24#-Nld7P47DKkqUnY5xafo:-NleEhbI2kZcUplItQFy:bfczoo3) ([raw file](https://github.com/ToyotaResearchInstitute/tri_hardware_drivers/blob/ada79b89aeb371bf214449c47b7dc98f73612ee8/schunk_wsg_driver/src/schunk_wsg_driver_node.ros1.cpp#L147)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

This doesn't take `local_port`
</blockquote></details>

Done, oops!
___
*[`schunk_wsg_driver/src/schunk_wsg_driver/schunk_wsg_driver_common.cpp` line 192 at r1](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24#-NlVPePl82kHh7FYUGy-:-NleEiVh0jGOq1nkpqxx:b303z43) ([raw file](https://github.com/ToyotaResearchInstitute/tri_hardware_drivers/blob/85078cda7019db407b1314eee43ba2a83c910716/schunk_wsg_driver/src/schunk_wsg_driver/schunk_wsg_driver_common.cpp#L192)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

So long as the behavior when running the driver directly (no script, normal ROS control) is OK, I think this is fine. There are some mentions in the documentation that suggest that stop and disconnect are the same for external control, but would produce different behavior with a script.
</blockquote></details>

Done. Tied it to 
___
*[`schunk_wsg_driver/src/schunk_wsg_driver/schunk_wsg_driver_ethernet.cpp` line 145 at r3](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24#-NldCFr71hFK5LGauwbb:-NleFAJUAuI52qX5O_FL:b-to1r7u) ([raw file](https://github.com/ToyotaResearchInstitute/tri_hardware_drivers/blob/ada79b89aeb371bf214449c47b7dc98f73612ee8/schunk_wsg_driver/src/schunk_wsg_driver/schunk_wsg_driver_ethernet.cpp#L145)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

This check should be the same for both UDP and TCP versions
</blockquote></details>

Done. Copied check to above, but only for using the check.
___
*[`schunk_wsg_driver/src/schunk_wsg_driver/schunk_wsg_driver_ethernet.cpp` line 242 at r3](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24#-NldAzBWBLEWPjgAR9TR:-NleFCjHByVmPQkGje4i:bd771d4) ([raw file](https://github.com/ToyotaResearchInstitute/tri_hardware_drivers/blob/ada79b89aeb371bf214449c47b7dc98f73612ee8/schunk_wsg_driver/src/schunk_wsg_driver/schunk_wsg_driver_ethernet.cpp#L242)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

btw elsewhere `close(socket)` gets used, this should be fine?
</blockquote></details>

Done. Removed comment.
___
*[`schunk_wsg_driver/src/schunk_wsg_driver/schunk_wsg_driver_ethernet.cpp` line 277 at r3](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24#-NldBZvy3gLvOIU61itw:-NleBXSrDun2NME2X6v7:bzgqr3l) ([raw file](https://github.com/ToyotaResearchInstitute/tri_hardware_drivers/blob/ada79b89aeb371bf214449c47b7dc98f73612ee8/schunk_wsg_driver/src/schunk_wsg_driver/schunk_wsg_driver_ethernet.cpp#L277)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

I believe you need to reenable `TCP_QUICKACK` [after the read](https://github.com/ToyotaResearchInstitute/tri_hardware_drivers/blob/master/dji_robomaster_ep_driver/src/dji_robomaster_ep_driver/dji_robomaster_ep_driver.cpp#L334-L387)
</blockquote></details>

Done. I did not need that for the gripper to work. Will try adding it in, though.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @calderpg-tri and @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24#-NleFFG05uvu5M7p1bGo:-NleGxWI4QX1vi8Lp49P:bqjv7jv) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Will re-test on Schunk.
</blockquote></details>

Changes between r3 and r5 make it such that I cannot restart the script.

My guess is either logic error on my revisions or the re-enabling of QUICKACK

___

**Review by calderpg-tri — COMMENTED** [review]
> Reviewed 1 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24#-NleFFG05uvu5M7p1bGo:-NleHxKT60OlmEA-j7rI:b3h8zhv) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Changes between r3 and r5 make it such that I cannot restart the script.

My guess is either logic error on my revisions or the re-enabling of QUICKACK
</blockquote></details>

`QUICKACK` shouldn't be the issue, since it was already enabled at the start. It needs to be reenabled for consistency because sometimes (but not always) it gets reset.

___

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @calderpg-tri)

*[a discussion](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24#-NleFFG05uvu5M7p1bGo:-NleIccTDe6wev4r6IIh:buk3f1e) (no related file):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

`QUICKACK` shouldn't be the issue, since it was already enabled at the start. It needs to be reenabled for consistency because sometimes (but not always) it gets reset.
</blockquote></details>

Done. I had inverted the boolean logic from `enable_recurring_status` to `use_scripting_interface`.
Now it works, and I can restart the driver (as long as I wait maybe 0.5 sec after stopping it)

___

**Review by calderpg-tri — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24#-:-NleKJtX4r8vCPsJY1Ul:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

___
*[`schunk_wsg_driver/include/schunk_wsg_driver/schunk_wsg_driver_common.hpp` line 401 at r3](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24#-Nld6SPs67-MKDMZbNqL:-NleJDgp95KTutP4dha4:b-cm0udf) ([raw file](https://github.com/ToyotaResearchInstitute/tri_hardware_drivers/blob/ada79b89aeb371bf214449c47b7dc98f73612ee8/schunk_wsg_driver/include/schunk_wsg_driver/schunk_wsg_driver_common.hpp#L401)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Since the scripting interface isn't part of this driver for now, I think it would be clearer to call this `use_external_scripting_interface_` and document `InitializeGripper` that this option involves and external component.
___
*[`schunk_wsg_driver/include/schunk_wsg_driver/schunk_wsg_driver_common.hpp` line 414 at r4](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24#-NleElDB82Dd3Coo-714:-NleJtlX03Nx4AHE-B4Z:b-w79buq) ([raw file](https://github.com/ToyotaResearchInstitute/tri_hardware_drivers/blob/a35fc0c36db510824e21c7592a0bb51e3cf20b89/schunk_wsg_driver/include/schunk_wsg_driver/schunk_wsg_driver_common.hpp#L414)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

FYI This setup is a bit convoluted; I am not sure if I should instead use a parameter struct to be more explicit, e.g.
```
struct InitializeGripperParam {
  uint16_t update_period_ms = 20;
  bool enable_recurring_status = true;
  GripperCommand stop_command = kStop;
};
```

Do you care for me to change it, or are you OK with me leaving this as-is?
</blockquote></details>

As-is is fine.

**Comment by EricCousineau-TRI** [comment]
*[`schunk_wsg_driver/include/schunk_wsg_driver/schunk_wsg_driver_common.hpp` line 401 at r3](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24#-Nld6SPs67-MKDMZbNqL:-NleLDgI9wP0o8pfJ2IK:b4666g5) ([raw file](https://github.com/ToyotaResearchInstitute/tri_hardware_drivers/blob/ada79b89aeb371bf214449c47b7dc98f73612ee8/schunk_wsg_driver/include/schunk_wsg_driver/schunk_wsg_driver_common.hpp#L401)):*
<details><summary><i>Previously, calderpg-tri wrote…</i></summary><blockquote>

Since the scripting interface isn't part of this driver for now, I think it would be clearer to call this `use_external_scripting_interface_` and document `InitializeGripper` that this option involves and external component.
</blockquote></details>

Hm... I'm struggling to imagine what would happen if/when we migrate the script here; does that mean we rewrite it?

I'd rather either keep it as `use_scripting_interface` and just update docstring, or be more explicit and expose `enable_recurring_status` and `stop_command` more directly.

Does that make sense? If so, which do you prefer?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24)* status: all files reviewed, 1 unresolved discussion (waiting on @calderpg-tri)

___
*[`schunk_wsg_driver/include/schunk_wsg_driver/schunk_wsg_driver_common.hpp` line 401 at r3](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24#-Nld6SPs67-MKDMZbNqL:-NleLZBdBQzQqBgrFcuj:b-v88zmk) ([raw file](https://github.com/ToyotaResearchInstitute/tri_hardware_drivers/blob/ada79b89aeb371bf214449c47b7dc98f73612ee8/schunk_wsg_driver/include/schunk_wsg_driver/schunk_wsg_driver_common.hpp#L401)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Hm... I'm struggling to imagine what would happen if/when we migrate the script here; does that mean we rewrite it?

I'd rather either keep it as `use_scripting_interface` and just update docstring, or be more explicit and expose `enable_recurring_status` and `stop_command` more directly.

Does that make sense? If so, which do you prefer?
</blockquote></details>

(not that renaming it is a huge deal)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @calderpg-tri)

___
*[`schunk_wsg_driver/include/schunk_wsg_driver/schunk_wsg_driver_common.hpp` line 401 at r3](https://reviewable.io/reviews/ToyotaResearchInstitute/tri_hardware_drivers/24#-Nld6SPs67-MKDMZbNqL:-NleMirp8pWM7RRU8Ej4:b2ys1to) ([raw file](https://github.com/ToyotaResearchInstitute/tri_hardware_drivers/blob/ada79b89aeb371bf214449c47b7dc98f73612ee8/schunk_wsg_driver/include/schunk_wsg_driver/schunk_wsg_driver_common.hpp#L401)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

(not that renaming it is a huge deal)
</blockquote></details>

OK Nevermind, going for `use_external_scripting_interface_` to keep it simple + move forward. Soz for perseverating

**Pull request merged**
